#!/usr/bin/env python

import pyinotify

wm = pyinotify.WatchManager()
mask = pyinotify.IN_DELETE | pyinotify.IN_CREATE | pyinotify.IN_MODIFY

class EventHandler(pyinotify.ProcessEvent):
	def process_IN_CREATE(self, event):
		print "creating %s \n" % ( event.pathname )
	
	def process_IN_MODIFY(self, event):
		print "modified %s \n" % ( event.pathname )	

	def process_IN_DELETE(self, event):
		print "deleting %s \n" % ( event.pathname )


handler = EventHandler()
notifier = pyinotify.Notifier(wm, handler)

wdd = wm.add_watch('./', mask, rec=True, )
notifier.loop()

