#!/usr/bin/env python
import sys, os
import sqlite3 as sq

from datetime import datetime as dt

class TodoDaemon:
	pass

def initialize():
    try:
	cc = sq.connect("todos.db")
	cr = cc.cursor()
	cr.execute(""" create table todos (project text, description text, status text, added text, updated text)""")
	cc.commit()
	cr.close()
	print "the sqlite todo's db is succesfully created!"

    except sq.OperationalError:
	print "the todos db already exists."

def getcursor():
	cc = sq.connect("todos.db")
	cr = cc.cursor()
	return cr

class Todo:
   def  __init__(self):
	self.cc = sq.connect("/home/chaitanya/Projects/scripts/todos.db")
	self.cr = self.cc.cursor()

   def execute(self, query):
	try:
		self.cr.execute(query)
	except sq.OperationalError:
		print "error occured while executing the sql-query."

   def addTodo(self):
	#project, description, status, 
	t = (sys.argv[2], sys.argv[3], "open", dt.now(), "")
	self.execute(""" insert into todos values (?, ?, ?, ?, ?) """, t)

	self.cc.commit()
	self.cr.close()

   def viewTodo(self):
	self.execute("""select * from todos""")

	for row in self.cr: print row

	self.cr.close()

if __name__ == '__main__':

	todo = Todo()

	if len(sys.argv) >= 2 and sys.argv[1] == 'initialize':
		initialize()
		sys.exit(0)

	if len(sys.argv) >= 2 and sys.argv[1] == 'showall':
		todo.viewTodo()
		sys.exit(0)

	if len(sys.argv) >= 4 and sys.argv[1] == 'add':
		todo.addTodo()
		sys.exit(0)

	print "help | usage | upcoming!"
	print
	sys.exit(-1)
